words = [
    "breakpoint",
    "colorschemes",
    "dap",
    "dapui",
    "esc",
    "frontmatter",
    "gitsigns",
    "guicursor",
    "keymaps",
    "lualine",
    "neotree",
    "nvim",
    "nzzzv",
    "stylua",
]
exclude_tags = ["identifier.function"]
