#
#
# unbinding
#
#

# Menus
unbind = SUPER, SPACE
unbind = SUPER CTRL, E
unbind = SUPER CTRL, C
unbind = SUPER CTRL, O
unbind = SUPER ALT, SPACE
unbind = SUPER, ESCAPE
unbind = , XF86PowerOff
unbind = SUPER, K
unbind = , XF86Calculator

# Aesthetics
unbind = SUPER SHIFT, SPACE
unbind = SUPER CTRL, SPACE
unbind = SUPER SHIFT CTRL, SPACE
unbind = SUPER, BACKSPACE
unbind = SUPER SHIFT, BACKSPACE
unbind = SUPER CTRL, BACKSPACE

# Notifications
unbind = SUPER, COMMA
unbind = SUPER SHIFT, COMMA
unbind = SUPER CTRL, COMMA
unbind = SUPER ALT, COMMA
unbind = SUPER SHIFT ALT, COMMA

# Toggles
unbind = SUPER CTRL, I
unbind = SUPER CTRL, N

# Control Apple Display brightness
unbind = CTRL, F1
unbind = CTRL, F2
unbind = SHIFT CTRL, F2

# Captures
unbind = , PRINT
unbind = ALT, PRINT
unbind = SUPER, PRINT

# File sharing
unbind = SUPER CTRL, S

# Waybar-less information
unbind = SUPER CTRL ALT, T
unbind = SUPER CTRL ALT, B

# Control panels
unbind = SUPER CTRL, A
unbind = SUPER CTRL, B
unbind = SUPER CTRL, W
unbind = SUPER CTRL, T

# Dictation
unbind = SUPER CTRL, X

# Zoom
unbind = SUPER CTRL, Z
unbind = SUPER CTRL ALT, Z

# Lock system
unbind = SUPER CTRL, L

#
#
# binding
#
#

bindd = , PRINT, Screenshot, exec, omarchy-cmd-screenshot
     
bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

bindd = ALT + SHIFT, A, Audio controls, exec, omarchy-launch-audio
bindd = ALT + SHIFT, S, Bluetooth controls, exec, omarchy-launch-bluetooth
bindd = CTRL + SHIFT, W, Launch apps, exec, omarchy-launch-walker
bindd = CTRL + SHIFT, K, Show key bindings, exec, omarchy-menu-keybindings
     
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
