unbind = SUPER, RETURN
unbind = SUPER SHIFT, RETURN
unbind = SUPER SHIFT, F
unbind = SUPER ALT SHIFT, F
unbind = SUPER SHIFT, B
unbind = SUPER SHIFT ALT, B
unbind = SUPER SHIFT, N

bindd = CTRL + SHIFT, T, Telegram, exec, omarchy-launch-or-focus Telegram
bindd = CTRL + SHIFT, F, Firefox, exec, omarchy-launch-or-focus firefox
bindd = CTRL + SHIFT, SPACE, ghostty, exec, omarchy-launch-or-focus ghostty 
bindd = CTRL + SHIFT, N, Nautilus, exec, uwsm-app -- nautilus --new-window
bindd = CTRL + SHIFT, S, Spotify, exec, omarchy-launch-or-focus spotify
bindd = CTRL + SHIFT, D, Discord, exec, omarchy-launch-or-focus discord

bindd = CTRL + SHIFT, M, Mic Toggle, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle 

binddp = ALT, z, Keyboard layout, exec, hyprctl switchxkblayout all next
