unbind = SUPER, RETURN
unbind = SUPER SHIFT, RETURN
unbind = SUPER SHIFT, F
unbind = SUPER ALT SHIFT, F
unbind = SUPER SHIFT, B
unbind = SUPER SHIFT ALT, B
unbind = SUPER SHIFT, N

bindd = CTRL + SHIFT, T, Telegram, exec, omarchy-launch-or-focus Telegram
bindd = CTRL + SHIFT, F, Firefox, exec, omarchy-launch-or-focus firefox
bindd = CTRL + SHIFT, SPACE, Tmux, exec, omarchy-launch-or-focus kitty 'uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux a 2>/dev/null || tmux'
bindd = CTRL + SHIFT, N, Nautilus, exec, uwsm-app -- nautilus --new-window
bindd = CTRL + SHIFT, D, Lazy Docker TUI, exec, omarchy-launch-tui lazydocker
bindd = ALT, z, Keyboard layout, exec, hyprctl switchxkblayout all next
